// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package openapi

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for Collection.
const (
	Russian Collection = "russian"
	World   Collection = "world"
)

// Valid indicates whether the value is a known member of the Collection enum.
func (e Collection) Valid() bool {
	switch e {
	case Russian:
		return true
	case World:
		return true
	default:
		return false
	}
}

// Defines values for FavoritesSort.
const (
	FavoritesSortArtist        FavoritesSort = "artist"
	FavoritesSortRecentlyAdded FavoritesSort = "recently_added"
	FavoritesSortTitle         FavoritesSort = "title"
	FavoritesSortYear          FavoritesSort = "year"
)

// Valid indicates whether the value is a known member of the FavoritesSort enum.
func (e FavoritesSort) Valid() bool {
	switch e {
	case FavoritesSortArtist:
		return true
	case FavoritesSortRecentlyAdded:
		return true
	case FavoritesSortTitle:
		return true
	case FavoritesSortYear:
		return true
	default:
		return false
	}
}

// Defines values for SearchMatchField.
const (
	SearchMatchFieldArtist      SearchMatchField = "artist"
	SearchMatchFieldDescription SearchMatchField = "description"
	SearchMatchFieldTags        SearchMatchField = "tags"
	SearchMatchFieldTitle       SearchMatchField = "title"
)

// Valid indicates whether the value is a known member of the SearchMatchField enum.
func (e SearchMatchField) Valid() bool {
	switch e {
	case SearchMatchFieldArtist:
		return true
	case SearchMatchFieldDescription:
		return true
	case SearchMatchFieldTags:
		return true
	case SearchMatchFieldTitle:
		return true
	default:
		return false
	}
}

// Defines values for TagType.
const (
	TagTypeCollection TagType = "collection"
	TagTypeGenre      TagType = "genre"
	TagTypePeriod     TagType = "period"
	TagTypeStyle      TagType = "style"
)

// Valid indicates whether the value is a known member of the TagType enum.
func (e TagType) Valid() bool {
	switch e {
	case TagTypeCollection:
		return true
	case TagTypeGenre:
		return true
	case TagTypePeriod:
		return true
	case TagTypeStyle:
		return true
	default:
		return false
	}
}

// Artist defines model for Artist.
type Artist struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// ArtworkDetail defines model for ArtworkDetail.
type ArtworkDetail struct {
	Artist      Artist     `json:"artist"`
	Collection  Collection `json:"collection"`
	Description string     `json:"description"`
	Facts       []string   `json:"facts"`
	Id          string     `json:"id"`
	ImageUrl    string     `json:"imageUrl"`
	IsFavorite  *bool      `json:"isFavorite,omitempty"`
	Tags        *[]Tag     `json:"tags,omitempty"`
	Title       string     `json:"title"`
	Year        int        `json:"year"`
}

// ArtworkSummary defines model for ArtworkSummary.
type ArtworkSummary struct {
	Artist     Artist `json:"artist"`
	Id         string `json:"id"`
	ImageUrl   string `json:"imageUrl"`
	IsFavorite *bool  `json:"isFavorite,omitempty"`
	Tags       *[]Tag `json:"tags,omitempty"`
	Title      string `json:"title"`
	Year       int    `json:"year"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken string `json:"accessToken"`

	// AccessTokenExpiresIn Access token lifetime in seconds.
	AccessTokenExpiresIn int    `json:"accessTokenExpiresIn"`
	RefreshToken         string `json:"refreshToken"`

	// RefreshTokenExpiresIn Refresh token lifetime in seconds.
	RefreshTokenExpiresIn int         `json:"refreshTokenExpiresIn"`
	TokenType             string      `json:"tokenType"`
	User                  UserProfile `json:"user"`
}

// CalendarItem defines model for CalendarItem.
type CalendarItem struct {
	ArtworkId string             `json:"artworkId"`
	Date      openapi_types.Date `json:"date"`
	ImageUrl  string             `json:"imageUrl"`
}

// CalendarResponse defines model for CalendarResponse.
type CalendarResponse struct {
	From  openapi_types.Date `json:"from"`
	Items []CalendarItem     `json:"items"`
	To    openapi_types.Date `json:"to"`
}

// Collection defines model for Collection.
type Collection string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string    `json:"code"`
	Details *[]string `json:"details,omitempty"`
	Message string    `json:"message"`
}

// FavoriteAddedResponse defines model for FavoriteAddedResponse.
type FavoriteAddedResponse struct {
	ArtworkId  string `json:"artworkId"`
	IsFavorite bool   `json:"isFavorite"`
	Success    bool   `json:"success"`
}

// FavoriteArtworkItem defines model for FavoriteArtworkItem.
type FavoriteArtworkItem struct {
	AddedAt    time.Time `json:"addedAt"`
	Artist     Artist    `json:"artist"`
	Id         string    `json:"id"`
	ImageUrl   string    `json:"imageUrl"`
	IsFavorite *bool     `json:"isFavorite,omitempty"`
	Tags       *[]Tag    `json:"tags,omitempty"`
	Title      string    `json:"title"`
	Year       int       `json:"year"`
}

// FavoriteMutationRequest defines model for FavoriteMutationRequest.
type FavoriteMutationRequest struct {
	ArtworkId string `json:"artworkId"`
}

// FavoriteRemovedResponse defines model for FavoriteRemovedResponse.
type FavoriteRemovedResponse struct {
	ArtworkId  string `json:"artworkId"`
	IsFavorite bool   `json:"isFavorite"`
	Success    bool   `json:"success"`
}

// FavoritesResponse defines model for FavoritesResponse.
type FavoritesResponse struct {
	Items      []FavoriteArtworkItem `json:"items"`
	Pagination Pagination            `json:"pagination"`
}

// FavoritesSort defines model for FavoritesSort.
type FavoritesSort string

// GalleryResponse defines model for GalleryResponse.
type GalleryResponse struct {
	Items      []ArtworkSummary `json:"items"`
	Pagination Pagination       `json:"pagination"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// MainResponse defines model for MainResponse.
type MainResponse struct {
	Date                openapi_types.Date `json:"date"`
	SelectedCollections []Collection       `json:"selectedCollections"`
	TodayArtwork        TodayArtwork       `json:"todayArtwork"`
	TodayStatus         TodayStatus        `json:"todayStatus"`
}

// MainViewRequest defines model for MainViewRequest.
type MainViewRequest struct {
	ArtworkId string             `json:"artworkId"`
	Date      openapi_types.Date `json:"date"`
}

// MainViewResponse defines model for MainViewResponse.
type MainViewResponse struct {
	HasViewedToday bool `json:"hasViewedToday"`
	Success        bool `json:"success"`
}

// NotificationSettings defines model for NotificationSettings.
type NotificationSettings struct {
	Enabled bool   `json:"enabled"`
	Time    string `json:"time"`

	// TimeZone IANA time zone used to interpret `time`.
	TimeZone string `json:"timeZone"`
}

// NotificationSettingsPatch defines model for NotificationSettingsPatch.
type NotificationSettingsPatch struct {
	Enabled *bool   `json:"enabled,omitempty"`
	Time    *string `json:"time,omitempty"`

	// TimeZone IANA time zone used to interpret `time`.
	TimeZone *string `json:"timeZone,omitempty"`
}

// NotificationStatusResponse defines model for NotificationStatusResponse.
type NotificationStatusResponse = TodayStatus

// Pagination defines model for Pagination.
type Pagination struct {
	Limit int `json:"limit"`
	Page  int `json:"page"`
	Total int `json:"total"`
}

// RefreshTokenRequest defines model for RefreshTokenRequest.
type RefreshTokenRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// RefreshTokenResponse defines model for RefreshTokenResponse.
type RefreshTokenResponse struct {
	AccessToken string `json:"accessToken"`

	// AccessTokenExpiresIn Access token lifetime in seconds.
	AccessTokenExpiresIn int    `json:"accessTokenExpiresIn"`
	RefreshToken         string `json:"refreshToken"`

	// RefreshTokenExpiresIn Refresh token lifetime in seconds.
	RefreshTokenExpiresIn int    `json:"refreshTokenExpiresIn"`
	TokenType             string `json:"tokenType"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// SearchArtworkItem defines model for SearchArtworkItem.
type SearchArtworkItem struct {
	Artist     Artist             `json:"artist"`
	Id         string             `json:"id"`
	ImageUrl   string             `json:"imageUrl"`
	IsFavorite *bool              `json:"isFavorite,omitempty"`
	MatchedBy  []SearchMatchField `json:"matchedBy"`
	Tags       *[]Tag             `json:"tags,omitempty"`
	Title      string             `json:"title"`
	Year       int                `json:"year"`
}

// SearchMatchField defines model for SearchMatchField.
type SearchMatchField string

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Items      []SearchArtworkItem `json:"items"`
	Pagination Pagination          `json:"pagination"`
}

// Settings defines model for Settings.
type Settings struct {
	Notifications       NotificationSettings `json:"notifications"`
	SelectedCollections []Collection         `json:"selectedCollections"`
}

// SettingsPatch defines model for SettingsPatch.
type SettingsPatch struct {
	Notifications       *NotificationSettingsPatch `json:"notifications,omitempty"`
	SelectedCollections *[]Collection              `json:"selectedCollections,omitempty"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	Success bool `json:"success"`
}

// Tag defines model for Tag.
type Tag struct {
	Id   string  `json:"id"`
	Name string  `json:"name"`
	Type TagType `json:"type"`
}

// TagType defines model for TagType.
type TagType string

// TagsResponse defines model for TagsResponse.
type TagsResponse struct {
	Items []Tag `json:"items"`
}

// TodayArtwork defines model for TodayArtwork.
type TodayArtwork = ArtworkDetail

// TodayStatus defines model for TodayStatus.
type TodayStatus struct {
	HasViewedToday bool   `json:"hasViewedToday"`
	Message        string `json:"message"`
	ShouldNotify   bool   `json:"shouldNotify"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Email     openapi_types.Email `json:"email"`
	Id        string              `json:"id"`
}

// ArtworkId defines model for ArtworkId.
type ArtworkId = string

// DateFrom defines model for DateFrom.
type DateFrom = openapi_types.Date

// DateTo defines model for DateTo.
type DateTo = openapi_types.Date

// Limit defines model for Limit.
type Limit = int

// Page defines model for Page.
type Page = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetGalleryArtworksParams defines parameters for GetGalleryArtworks.
type GetGalleryArtworksParams struct {
	// Page Page number.
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Collection Filter artworks by collection.
	Collection *Collection `form:"collection,omitempty" json:"collection,omitempty"`

	// TagId Filter artworks by tag identifier.
	TagId *string `form:"tagId,omitempty" json:"tagId,omitempty"`
}

// SearchArtworksParams defines parameters for SearchArtworks.
type SearchArtworksParams struct {
	// Q Search query.
	Q string `form:"q" json:"q"`

	// Page Page number.
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetCalendarParams defines parameters for GetCalendar.
type GetCalendarParams struct {
	// From Inclusive start of the calendar range. Must be used together with `to`.
	From *DateFrom `form:"from,omitempty" json:"from,omitempty"`

	// To Inclusive end of the calendar range. Must be used together with `from` and must not be earlier than it.
	To *DateTo `form:"to,omitempty" json:"to,omitempty"`
}

// GetFavoritesParams defines parameters for GetFavorites.
type GetFavoritesParams struct {
	// Page Page number.
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Q Search within favorites.
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Sort Sorting mode.
	Sort *FavoritesSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// LogoutUserJSONRequestBody defines body for LogoutUser for application/json ContentType.
type LogoutUserJSONRequestBody = RefreshTokenRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// RefreshAccessTokenJSONRequestBody defines body for RefreshAccessToken for application/json ContentType.
type RefreshAccessTokenJSONRequestBody = RefreshTokenRequest

// AddFavoriteJSONRequestBody defines body for AddFavorite for application/json ContentType.
type AddFavoriteJSONRequestBody = FavoriteMutationRequest

// MarkTodayArtworkViewedJSONRequestBody defines body for MarkTodayArtworkViewed for application/json ContentType.
type MarkTodayArtworkViewedJSONRequestBody = MainViewRequest

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody = SettingsPatch

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get gallery artworks
	// (GET /artworks/gallery)
	GetGalleryArtworks(w http.ResponseWriter, r *http.Request, params GetGalleryArtworksParams)
	// Search artworks
	// (GET /artworks/search)
	SearchArtworks(w http.ResponseWriter, r *http.Request, params SearchArtworksParams)
	// Get artwork details
	// (GET /artworks/{artworkId})
	GetArtworkById(w http.ResponseWriter, r *http.Request, artworkId ArtworkId)
	// Log in
	// (POST /auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// Log out
	// (POST /auth/logout)
	LogoutUser(w http.ResponseWriter, r *http.Request)
	// Register a user
	// (POST /auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// Refresh access token
	// (POST /auth/token/refresh)
	RefreshAccessToken(w http.ResponseWriter, r *http.Request)
	// Get artwork calendar
	// (GET /calendar)
	GetCalendar(w http.ResponseWriter, r *http.Request, params GetCalendarParams)
	// Get favorite artworks
	// (GET /favorites)
	GetFavorites(w http.ResponseWriter, r *http.Request, params GetFavoritesParams)
	// Add artwork to favorites
	// (POST /favorites)
	AddFavorite(w http.ResponseWriter, r *http.Request)
	// Remove artwork from favorites
	// (DELETE /favorites/{artworkId})
	RemoveFavorite(w http.ResponseWriter, r *http.Request, artworkId ArtworkId)
	// Get home screen data
	// (GET /main)
	GetMain(w http.ResponseWriter, r *http.Request)
	// Mark the artwork of the day as viewed
	// (POST /main/view)
	MarkTodayArtworkViewed(w http.ResponseWriter, r *http.Request)
	// Get today's notification status
	// (GET /notifications/today-status)
	GetTodayNotificationStatus(w http.ResponseWriter, r *http.Request)
	// Get user settings
	// (GET /settings)
	GetSettings(w http.ResponseWriter, r *http.Request)
	// Update user settings
	// (PATCH /settings)
	UpdateSettings(w http.ResponseWriter, r *http.Request)
	// Get tags
	// (GET /tags)
	GetTags(w http.ResponseWriter, r *http.Request)
	// Get current user profile
	// (GET /users/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get gallery artworks
// (GET /artworks/gallery)
func (_ Unimplemented) GetGalleryArtworks(w http.ResponseWriter, r *http.Request, params GetGalleryArtworksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search artworks
// (GET /artworks/search)
func (_ Unimplemented) SearchArtworks(w http.ResponseWriter, r *http.Request, params SearchArtworksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get artwork details
// (GET /artworks/{artworkId})
func (_ Unimplemented) GetArtworkById(w http.ResponseWriter, r *http.Request, artworkId ArtworkId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Log in
// (POST /auth/login)
func (_ Unimplemented) LoginUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Log out
// (POST /auth/logout)
func (_ Unimplemented) LogoutUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a user
// (POST /auth/register)
func (_ Unimplemented) RegisterUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh access token
// (POST /auth/token/refresh)
func (_ Unimplemented) RefreshAccessToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get artwork calendar
// (GET /calendar)
func (_ Unimplemented) GetCalendar(w http.ResponseWriter, r *http.Request, params GetCalendarParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get favorite artworks
// (GET /favorites)
func (_ Unimplemented) GetFavorites(w http.ResponseWriter, r *http.Request, params GetFavoritesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add artwork to favorites
// (POST /favorites)
func (_ Unimplemented) AddFavorite(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove artwork from favorites
// (DELETE /favorites/{artworkId})
func (_ Unimplemented) RemoveFavorite(w http.ResponseWriter, r *http.Request, artworkId ArtworkId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get home screen data
// (GET /main)
func (_ Unimplemented) GetMain(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Mark the artwork of the day as viewed
// (POST /main/view)
func (_ Unimplemented) MarkTodayArtworkViewed(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get today's notification status
// (GET /notifications/today-status)
func (_ Unimplemented) GetTodayNotificationStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user settings
// (GET /settings)
func (_ Unimplemented) GetSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update user settings
// (PATCH /settings)
func (_ Unimplemented) UpdateSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get tags
// (GET /tags)
func (_ Unimplemented) GetTags(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user profile
// (GET /users/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetGalleryArtworks operation middleware
func (siw *ServerInterfaceWrapper) GetGalleryArtworks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGalleryArtworksParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "collection" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "collection", r.URL.Query(), &params.Collection, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "collection"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "collection", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tagId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tagId", r.URL.Query(), &params.TagId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tagId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tagId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGalleryArtworks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchArtworks operation middleware
func (siw *ServerInterfaceWrapper) SearchArtworks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchArtworksParams

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchArtworks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArtworkById operation middleware
func (siw *ServerInterfaceWrapper) GetArtworkById(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "artworkId" -------------
	var artworkId ArtworkId

	err = runtime.BindStyledParameterWithOptions("simple", "artworkId", chi.URLParam(r, "artworkId"), &artworkId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artworkId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArtworkById(w, r, artworkId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LogoutUser operation middleware
func (siw *ServerInterfaceWrapper) LogoutUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshAccessToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshAccessToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshAccessToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCalendar operation middleware
func (siw *ServerInterfaceWrapper) GetCalendar(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCalendarParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCalendar(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFavorites operation middleware
func (siw *ServerInterfaceWrapper) GetFavorites(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFavoritesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFavorites(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddFavorite operation middleware
func (siw *ServerInterfaceWrapper) AddFavorite(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddFavorite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveFavorite operation middleware
func (siw *ServerInterfaceWrapper) RemoveFavorite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "artworkId" -------------
	var artworkId ArtworkId

	err = runtime.BindStyledParameterWithOptions("simple", "artworkId", chi.URLParam(r, "artworkId"), &artworkId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artworkId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveFavorite(w, r, artworkId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMain operation middleware
func (siw *ServerInterfaceWrapper) GetMain(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMain(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MarkTodayArtworkViewed operation middleware
func (siw *ServerInterfaceWrapper) MarkTodayArtworkViewed(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MarkTodayArtworkViewed(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTodayNotificationStatus operation middleware
func (siw *ServerInterfaceWrapper) GetTodayNotificationStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTodayNotificationStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTags operation middleware
func (siw *ServerInterfaceWrapper) GetTags(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTags(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/artworks/gallery", wrapper.GetGalleryArtworks)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/artworks/search", wrapper.SearchArtworks)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/artworks/{artworkId}", wrapper.GetArtworkById)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.LoginUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.LogoutUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.RegisterUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/token/refresh", wrapper.RefreshAccessToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/calendar", wrapper.GetCalendar)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/favorites", wrapper.GetFavorites)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/favorites", wrapper.AddFavorite)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/favorites/{artworkId}", wrapper.RemoveFavorite)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/main", wrapper.GetMain)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/main/view", wrapper.MarkTodayArtworkViewed)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/notifications/today-status", wrapper.GetTodayNotificationStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/settings", wrapper.GetSettings)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/settings", wrapper.UpdateSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tags", wrapper.GetTags)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/me", wrapper.GetCurrentUser)
	})

	return r
}
